### ISSUE TITLE
Arrow keys to navigate each slide not working.

### ISSUE THREAD

**Issue by kwuster** [LinkedInLearning/tailwind-css-2841311#2]
## Issue Overview

Arrow keys to navigate each slide does not work.

## Describe your environment

Mac OS 10.15.4
Safari 13.1 (15609.1.20.111.8)
Chrome (Version 90.0.4430.93)
Firefox  (v85.0.2)

## Steps to Reproduce

1. Use the arrows to navigate the slides on all major browsers.

## Expected Behavior

- Slides will advance & return the next or previous slide respectively.

**Comment by planetoftheweb** [comment]
Which slide were you on? Did you hit the M key from the home page to see the slide menu, or was it one of the slides from the videos that isn't working for you. Send me the link to the slide so I can take a look.

**Comment by kwuster** [comment]
It looks to be the single-slide topics that seem to be the issue. The other slides seem to work fine now that I've checked the other topics. I think this is probably more of a usability issue.

May I suggest:

- some indication telling the user has reached the end of a topic.
- the ability to go from the end of one topic and flow to the next topic using the arrows keys could be useful.

Consider this topic closed Ray. Thanks.
